name: 'Safe Git Push'
description: 'Commit and push changes with automatic conflict resolution'
inputs:
  commit-message:
    description: 'Commit message'
    required: true
  files:
    description: 'Files to add (space-separated or glob pattern)'
    required: true
  max-retries:
    description: 'Maximum retry attempts'
    default: '5'
  allow-empty:
    description: 'Allow empty commits'
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Commit and push with retry
      shell: bash
      run: |
        set +e
        
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        echo "📦 Adding files..."
        FILES_ADDED=0
        
        for pattern in ${{ inputs.files }}; do
          echo "  Checking: $pattern"
          
          if compgen -G "$pattern" > /dev/null 2>&1; then
            git add "$pattern" 2>/dev/null && {
              FILES_ADDED=1
              echo "    ✅ Added: $pattern"
            } || echo "    ⚠️  Failed to add: $pattern"
          else
            if [ -e "$pattern" ]; then
              git add "$pattern" 2>/dev/null && {
                FILES_ADDED=1
                echo "    ✅ Added: $pattern"
              } || echo "    ⚠️  Failed to add: $pattern"
            else
              echo "    ⏭️  Not found: $pattern (skipping)"
            fi
          fi
        done
        
        if git diff --staged --quiet; then
          if [ "${{ inputs.allow-empty }}" = "true" ]; then
            echo "⚠️  No changes to commit (allow-empty is true)"
            git commit --allow-empty -m "${{ inputs.commit-message }}"
          else
            echo "⚠️  No changes to commit"
            exit 0
          fi
        else
          echo "✅ Changes staged, creating commit..."
          git commit -m "${{ inputs.commit-message }}" || {
            echo "⚠️  Commit failed"
            exit 0
          }
        fi
        
        echo "🚀 Pushing changes..."
        MAX_RETRIES=${{ inputs.max-retries }}
        RETRY_COUNT=0
        
        while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
          if git push; then
            echo "✅ Changes pushed successfully"
            exit 0
          else
            RETRY_COUNT=$((RETRY_COUNT + 1))
            if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
              echo "⚠️  Push failed, retrying ($RETRY_COUNT/$MAX_RETRIES)..."
              
              SLEEP_TIME=$((RETRY_COUNT * 2))
              echo "   Waiting ${SLEEP_TIME}s before retry..."
              sleep $SLEEP_TIME
              
              BRANCH_NAME="${GITHUB_REF##*/}"
              echo "   Pulling latest changes from $BRANCH_NAME..."
              
              git fetch origin "$BRANCH_NAME"
              
              echo "   🧹 Handling untracked files..."
              UNTRACKED_FILES=$(git ls-files --others --exclude-standard)
              
              if [ -n "$UNTRACKED_FILES" ]; then
                echo "   📦 Stashing untracked files..."
                TEMP_DIR=".git/untracked-backup-$(date +%s)"
                mkdir -p "$TEMP_DIR"
                
                while IFS= read -r file; do
                  if [ -f "$file" ]; then
                    mkdir -p "$TEMP_DIR/$(dirname "$file")"
                    mv "$file" "$TEMP_DIR/$file"
                    echo "     Moved: $file"
                  fi
                done <<< "$UNTRACKED_FILES"
              fi
              
              if git pull --rebase origin "$BRANCH_NAME" 2>&1; then
                echo "   ✅ Rebased successfully"
              else
                echo "   ⚠️  Rebase failed, trying merge..."
                git rebase --abort 2>/dev/null || true
                
                if git pull --no-rebase origin "$BRANCH_NAME" 2>&1; then
                  echo "   ✅ Merged successfully"
                else
                  echo "   ❌ Both rebase and merge failed"
                  
                  if [ -d "$TEMP_DIR" ]; then
                    echo "   🔄 Restoring untracked files..."
                    cp -r "$TEMP_DIR"/* ./ 2>/dev/null || true
                    rm -rf "$TEMP_DIR"
                  fi
                  
                  git status
                  exit 1
                fi
              fi
              
              if [ -d "$TEMP_DIR" ]; then
                echo "   🔄 Restoring untracked files..."
                find "$TEMP_DIR" -type f | while read -r backup_file; do
                  original_file="${backup_file#$TEMP_DIR/}"
                  if [ ! -e "$original_file" ]; then
                    mkdir -p "$(dirname "$original_file")"
                    mv "$backup_file" "$original_file"
                    echo "     Restored: $original_file"
                  else
                    echo "     Skipped (exists): $original_file"
                  fi
                done
                rm -rf "$TEMP_DIR"
              fi
              
            else
              echo "❌ Failed to push after $MAX_RETRIES attempts"
              git status
              exit 1
            fi
          fi
        done
