# LinkedIn Automation Configuration
# Version: 1.0
# Last Updated: 2025-10-07

# =============================================================================
# SYSTEM SETTINGS
# =============================================================================
system:
  data_directory: "job_search"
  backup_enabled: true
  backup_frequency: "daily"
  log_level: "INFO"
  timezone: "UTC"

# =============================================================================
# RATE LIMITS (Conservative to avoid LinkedIn restrictions)
# =============================================================================
rate_limits:
  daily:
    connections: 5          # Max new connection requests per day
    messages: 10            # Max direct messages per day
    profile_views: 50       # Max profile views per day
    
  weekly:
    connections: 35         # Max connection requests per week
    
  delays:
    min_action_delay: 30    # Minimum seconds between actions
    max_action_delay: 120   # Maximum seconds between actions
    human_like: true        # Add random delays to simulate human behavior

# =============================================================================
# TARGET INDUSTRIES & SPECIALIZATIONS
# =============================================================================
industries:
  data_science_ai:
    name: "Data Science & AI/ML"
    enabled: true
    titles:
      - "Data Scientist"
      - "Machine Learning Engineer"
      - "AI Engineer"
      - "ML Research Scientist"
      - "Applied Scientist"
      - "Research Engineer"
      - "Deep Learning Engineer"
      - "NLP Engineer"
      - "Computer Vision Engineer"
      - "AI Product Manager"
      - "Head of AI"
      - "Director of Machine Learning"
      - "Staff Machine Learning Engineer"
      - "Principal Data Scientist"
    
    companies:
      - "OpenAI"
      - "Anthropic"
      - "Google DeepMind"
      - "Meta AI"
      - "Microsoft Research"
      - "Amazon AWS AI"
      - "Scale AI"
      - "Hugging Face"
      - "Cohere"
      - "Stability AI"
      - "DataRobot"
      - "Databricks"
      - "Snowflake"
      - "Palantir"
      - "C3.AI"
    
    keywords:
      - "LLM"
      - "GPT"
      - "Transformer"
      - "PyTorch"
      - "TensorFlow"
      - "MLOps"
      - "Computer Vision"
      - "NLP"
      - "Reinforcement Learning"
      - "GenAI"

  finance:
    name: "Finance & Quantitative Analysis"
    enabled: true
    titles:
      - "Quantitative Analyst"
      - "Quantitative Researcher"
      - "Quant Developer"
      - "Risk Analyst"
      - "Portfolio Manager"
      - "Financial Engineer"
      - "Investment Analyst"
      - "Equity Research Analyst"
      - "Credit Analyst"
      - "VP of Quantitative Research"
      - "Head of Risk"
      - "Chief Risk Officer"
    
    companies:
      - "Jane Street"
      - "Citadel"
      - "Two Sigma"
      - "Renaissance Technologies"
      - "DE Shaw"
      - "Jump Trading"
      - "Goldman Sachs"
      - "Morgan Stanley"
      - "JPMorgan"
      - "Blackrock"
      - "Bridgewater"
      - "AQR Capital"
    
    keywords:
      - "Quantitative Finance"
      - "Risk Management"
      - "Portfolio Optimization"
      - "Derivatives"
      - "Fixed Income"
      - "Credit Risk"
      - "Market Risk"

  trading:
    name: "Trading & Market Making"
    enabled: true
    titles:
      - "Quantitative Trader"
      - "Algorithmic Trader"
      - "High Frequency Trader"
      - "Options Trader"
      - "Market Maker"
      - "Prop Trader"
      - "Systematic Trader"
      - "Head of Trading"
      - "Trading Strategist"
      - "Execution Trader"
    
    companies:
      - "Citadel Securities"
      - "Jane Street"
      - "Virtu Financial"
      - "Jump Trading"
      - "Tower Research"
      - "Hudson River Trading"
      - "IMC Trading"
      - "Optiver"
      - "SIG (Susquehanna)"
      - "DRW Trading"
      - "Flow Traders"
      - "Akuna Capital"
    
    keywords:
      - "HFT"
      - "Market Making"
      - "Algo Trading"
      - "Order Execution"
      - "Quantitative Trading"
      - "Statistical Arbitrage"
      - "Options Trading"

# =============================================================================
# CAMPAIGN SETTINGS
# =============================================================================
campaigns:
  default_daily_target: 3
  priority_levels:
    - high
    - medium
    - low
  
  target_levels:
    - entry
    - mid
    - senior
    - executive
  
  auto_create_followup: true
  track_mutual_connections: true

# =============================================================================
# MESSAGE TEMPLATES
# =============================================================================
message_templates:
  connection_request:
    data_science_ai:
      - "Hi {first_name},\n\nI came across your work at {company} and was impressed by your experience in {position}. I'm exploring opportunities in ML/AI and would love to connect and learn from your journey in the field.\n\nLooking forward to connecting!"
      
      - "Hi {first_name},\n\nYour background in AI at {company} caught my attention. I'm particularly interested in {interest_area}. Would love to connect and exchange insights about the field.\n\nBest regards!"
      
      - "Hi {first_name},\n\nI noticed your role as {position} at {company}. As someone passionate about ML/AI, I'd appreciate the opportunity to connect and learn about {company}'s approach to AI innovation.\n\nThanks for considering!"
    
    finance:
      - "Hi {first_name},\n\nYour experience in quantitative finance at {company} is impressive. I'm pursuing opportunities in quant research/development and would greatly appreciate connecting to learn from your expertise.\n\nLooking forward to it!"
      
      - "Hi {first_name},\n\nI came across your profile and was struck by your work at {company}. I'm interested in {interest_area} and would value connecting with someone with your background.\n\nBest regards!"
      
      - "Hi {first_name},\n\nAs someone exploring quantitative finance, I'm impressed by your role at {company}. Would love to connect and learn about your path in the industry.\n\nThank you!"
    
    trading:
      - "Hi {first_name},\n\nYour experience in systematic trading at {company} is fascinating. I'm exploring opportunities in algo trading and would appreciate connecting to learn from your journey.\n\nLooking forward to connecting!"
      
      - "Hi {first_name},\n\nI noticed your background in {position} at {company}. As someone interested in quantitative trading strategies, I'd value the opportunity to connect and learn from your experience.\n\nBest regards!"
      
      - "Hi {first_name},\n\nYour work at {company} caught my attention. I'm passionate about algorithmic trading and would appreciate connecting to exchange insights about the field.\n\nThank you for considering!"

  follow_up_sequence:
    day_3_thank_you:
      - "Hi {first_name},\n\nThanks for connecting! I'm curious about {company}'s approach to {topic}. Would you be open to a brief 15-minute chat about your experience?\n\nBest regards"
    
    day_14_value_share:
      - "Hi {first_name},\n\nI recently came across this interesting {content_type} on {topic} and thought you might find it valuable given your work at {company}.\n\n[Link would go here]\n\nWould love to hear your thoughts!"
    
    day_30_informational:
      - "Hi {first_name},\n\nI hope you're doing well! I'm exploring {role_type} roles and would greatly appreciate 15 minutes of your time to learn about your career path and {company}'s team culture.\n\nWould next week work for a quick call?"

# =============================================================================
# INTEREST AREAS (for personalization)
# =============================================================================
interest_areas:
  ai_ml:
    - "LLM fine-tuning and deployment"
    - "reinforcement learning applications"
    - "computer vision systems"
    - "NLP and transformer architectures"
    - "MLOps and model deployment"
    - "generative AI applications"
  
  finance:
    - "quantitative risk management"
    - "portfolio optimization strategies"
    - "derivative pricing models"
    - "statistical arbitrage"
    - "credit risk modeling"
    - "systematic trading strategies"

# =============================================================================
# FOLLOW-UP STRATEGY
# =============================================================================
follow_up_strategy:
  sequence_enabled: true
  auto_schedule: true
  
  timeline:
    first_message: 3        # Days after connection
    second_message: 14      # Days after connection
    third_message: 30       # Days after connection
  
  message_types:
    - thank_you
    - value_share
    - informational
  
  stop_on_response: true
  max_attempts: 3

# =============================================================================
# ENGAGEMENT STRATEGY
# =============================================================================
engagement:
  profile_views:
    enabled: true
    view_pending_connections: true
    days_before_followup: 7
  
  content_interaction:
    enabled: true
    like_posts: true
    comment_on_posts: false  # Requires manual action
    share_content: false
  
  value_sharing:
    share_articles: true
    share_insights: true
    frequency: "weekly"

# =============================================================================
# PRIORITY RULES
# =============================================================================
priority_rules:
  high_priority_criteria:
    - has_mutual_connections: true
    - min_mutual_connections: 2
    - target_company_match: true
    - recent_activity: true
  
  sorting:
    primary: "priority"
    secondary: "mutual_connections"
    tertiary: "added_date"

# =============================================================================
# TRACKING & ANALYTICS
# =============================================================================
tracking:
  enabled: true
  
  metrics:
    - connection_acceptance_rate
    - message_response_rate
    - meeting_conversion_rate
    - industry_breakdown
    - campaign_performance
    - weekly_progress
  
  reports:
    daily: true
    weekly: true
    monthly: true
  
  export_formats:
    - json
    - csv

# =============================================================================
# DATA PERSISTENCE
# =============================================================================
data_files:
  activity: "linkedin_advanced_activity.json"
  targets: "linkedin_targets.json"
  campaigns: "linkedin_campaigns.json"
  conversations: "linkedin_conversations.json"
  
  backup_directory: "backups"
  retention_days: 90

# =============================================================================
# WORKFLOW AUTOMATION
# =============================================================================
workflows:
  morning_routine:
    enabled: true
    time: "09:00"
    actions:
      - reset_daily_limits
      - generate_daily_tasks
      - prepare_connection_messages
  
  evening_routine:
    enabled: true
    time: "18:00"
    actions:
      - generate_daily_report
      - backup_data
      - schedule_next_day
  
  weekly_review:
    enabled: true
    day: "sunday"
    time: "19:00"
    actions:
      - generate_weekly_report
      - analyze_campaigns
      - adjust_strategy

# =============================================================================
# SAFETY & COMPLIANCE
# =============================================================================
safety:
  respect_linkedin_tos: true
  manual_confirmation: true      # Require manual action for connections
  avoid_spam_behavior: true
  personalize_all_messages: true
  
  warnings:
    daily_limit_warning: 0.8     # Warn at 80% of daily limit
    weekly_limit_warning: 0.9    # Warn at 90% of weekly limit
  
  cooldown_periods:
    after_limit_reached: 24      # Hours to wait
    between_campaigns: 1         # Days between campaigns

# =============================================================================
# NOTIFICATION SETTINGS
# =============================================================================
notifications:
  enabled: true
  
  events:
    connection_accepted: true
    message_received: true
    meeting_scheduled: true
    daily_limit_reached: true
    weekly_limit_reached: true
  
  channels:
    console: true
    email: false
    webhook: false

# =============================================================================
# ADVANCED FEATURES
# =============================================================================
advanced:
  ai_personalization: false      # Future: Use AI for message customization
  sentiment_analysis: false      # Future: Analyze response sentiment
  ab_testing: false              # Future: Test different message templates
  predictive_scoring: false      # Future: Score connection likelihood
  
  integrations:
    calendar: false              # Future: Calendar integration for meetings
    crm: false                   # Future: CRM integration
    email: false                 # Future: Email follow-ups

# =============================================================================
# USER PREFERENCES
# =============================================================================
user_preferences:
  preferred_contact_time: "morning"
  timezone_aware: true
  language: "en"
  
  profile:
    current_title: ""
    target_roles: []
    industries_of_interest: []
    geographic_preference: []

# =============================================================================
# DEBUGGING & DEVELOPMENT
# =============================================================================
debug:
  enabled: false
  verbose_logging: false
  dry_run_mode: false            # Test without making actual changes
  mock_responses: false
  
  test_data:
    generate_sample_campaigns: false
    generate_sample_targets: false
