name: Send CV Match Emails

on:
  workflow_run:
    workflows: ["CV Job Matcher - Enhanced Automation"]
    types:
      - completed

jobs:
  send-emails:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: job-match-reports
      
      - name: Check for queued emails
        id: check_queue
        run: |
          if [ -d "github_actions_emails" ] && [ "$(ls -A github_actions_emails 2>/dev/null)" ]; then
            echo "emails_exist=true" >> $GITHUB_OUTPUT
            email_count=$(find github_actions_emails -name "*.json" | wc -l)
            echo "email_count=$email_count" >> $GITHUB_OUTPUT
            echo "Found $email_count queued emails"
          else
            echo "emails_exist=false" >> $GITHUB_OUTPUT
            echo "email_count=0" >> $GITHUB_OUTPUT
            echo "No queued emails found"
          fi
      
      - name: Send queued emails
        if: steps.check_queue.outputs.emails_exist == 'true'
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.SMTP_SERVER || 'smtp.gmail.com' }}
          server_port: ${{ secrets.SMTP_PORT || '587' }}
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "CV Job Match Analysis Complete 🎯"
          to: ${{ secrets.NOTIFICATION_EMAIL }}
          from: ${{ secrets.SMTP_USER }}
          html_body: file://job_match_email.html
          attachments: |
            reports/*.txt
            reports/*.json
          ignore_cert: true
          convert_markdown: true
      
      - name: Process individual emails
        if: steps.check_queue.outputs.emails_exist == 'true'
        run: |
          echo "Processing ${{ steps.check_queue.outputs.email_count }} queued emails..."
          
          for email_file in github_actions_emails/*.json; do
            if [ -f "$email_file" ]; then
              echo "Processing: $email_file"
              # Extract email data
